# Generated by Django 5.2.10 on 2026-02-02 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='catalog.categoria', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Código único del producto', max_length=50, unique=True, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('filtro_1', models.CharField(blank=True, max_length=200, verbose_name='Filtro 1')),
                ('filtro_2', models.CharField(blank=True, max_length=200, verbose_name='Filtro 2')),
                ('filtro_3', models.CharField(blank=True, max_length=200, verbose_name='Filtro 3')),
                ('filtro_4', models.CharField(blank=True, max_length=200, verbose_name='Filtro 4')),
                ('filtro_5', models.CharField(blank=True, max_length=200, verbose_name='Filtro 5')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('categorias', models.ManyToManyField(blank=True, related_name='productos', to='catalog.categoria', verbose_name='Categorías')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionFiltro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(choices=[('filtro_1', 'Filtro 1'), ('filtro_2', 'Filtro 2'), ('filtro_3', 'Filtro 3'), ('filtro_4', 'Filtro 4'), ('filtro_5', 'Filtro 5')], max_length=50, verbose_name='Campo')),
                ('etiqueta', models.CharField(help_text='Nombre visible del filtro (ej: "Diámetro", "Material")', max_length=100, verbose_name='Etiqueta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_filtros', to='catalog.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Configuración de Filtro',
                'verbose_name_plural': 'Configuraciones de Filtros',
                'ordering': ['orden'],
                'unique_together': {('categoria', 'nombre_campo')},
            },
        ),
    ]
