# Generated by Django 5.2.10 on 2026-02-02 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinicionAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Identificador único (ej: tipo_fabricacion)', max_length=50, verbose_name='Nombre interno')),
                ('etiqueta', models.CharField(help_text='Nombre visible (ej: Tipo de Fabricación)', max_length=100, verbose_name='Etiqueta')),
                ('tipo', models.CharField(choices=[('texto', 'Texto libre'), ('lista', 'Lista de opciones'), ('numero', 'Número')], default='texto', max_length=20, verbose_name='Tipo de dato')),
                ('opciones', models.JSONField(blank=True, default=list, help_text='Para tipo "lista": ["opcion1", "opcion2", ...]', verbose_name='Opciones')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('mostrar_en_filtros', models.BooleanField(default=True, verbose_name='Mostrar en filtros')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definiciones_atributos', to='catalog.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Definición de Atributo',
                'verbose_name_plural': 'Definiciones de Atributos',
                'ordering': ['categoria', 'orden'],
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ProductoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=500, verbose_name='Valor')),
                ('definicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='catalog.definicionatributo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='catalog.producto')),
            ],
            options={
                'verbose_name': 'Atributo de Producto',
                'verbose_name_plural': 'Atributos de Productos',
                'unique_together': {('producto', 'definicion')},
            },
        ),
    ]
