# Generated by Django 5.2.10 on 2026-02-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_definicionatributo_productoatributo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productoatributo',
            index=models.Index(fields=['definicion', 'valor'], name='catalog_pro_definic_84506a_idx'),
        ),
    ]
