# Generated by Django 5.2.10 on 2026-02-02 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('productos', 'Productos'), ('clientes', 'Clientes'), ('categorias', 'Categorías')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='imports/logs/')),
                ('total_filas', models.IntegerField(default=0)),
                ('creados', models.IntegerField(default=0)),
                ('actualizados', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('procesados', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Importación',
                'verbose_name_plural': 'Logs de Importación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField()),
                ('columna', models.CharField(blank=True, max_length=100)),
                ('valor', models.CharField(blank=True, max_length=500)),
                ('mensaje', models.TextField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores_detalle', to='imports.importlog')),
            ],
            options={
                'verbose_name': 'Error de Importación',
                'verbose_name_plural': 'Errores de Importación',
                'ordering': ['fila'],
            },
        ),
    ]
