# Generated by Django 5.2.10 on 2026-02-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='tipo',
            field=models.CharField(choices=[('productos', 'Productos'), ('clientes', 'Clientes'), ('categorias', 'Categorías'), ('abrazaderas', 'Abrazaderas')], max_length=20),
        ),
    ]
